on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from Changes.md
        id: get_version
        run: |
          VERSION=v$(grep -oE '^##[[:space:]]*[0-9]+\.[0-9]+\.[0-9]+' Changes.md | head -n1 | sed 's/^##[[:space:]]*//')
          if [ -z "$VERSION" ]; then
            echo "No version found in Changes.md" >&2
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Extracted version: $VERSION"

      - name: Create git tag if not exists
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          TAG="v${{ steps.get_version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping tag creation."
          else
            git tag "$TAG"
            git push origin "$TAG"
            echo "Tag $TAG created and pushed."
          fi

  release:
    name: Release - ${{ matrix.platform.os-name }}
    needs: tag
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          # - os-name: Linux-aarch64
          #   runs-on: ubuntu-24.04
          #   target: aarch64-unknown-linux-musl
          #
          # - os-name: Windows-x86_64
          #   runs-on: windows-latest
          #   target: x86_64-pc-windows-msvc
          #
          # - os-name: Windows-aarch64
          #   runs-on: windows-latest
          #   target: aarch64-pc-windows-msvc
          #
          # - os-name: macOS-x86_64
          #   runs-on: macOS-latest
          #   target: x86_64-apple-darwin
          #
          # - os-name: macOS-aarch64
          #   runs-on: macOS-latest
          #   target: aarch64-apple-darwin
          #
          # - os-name: FreeBSD-x86_64
          #   runs-on: ubuntu-24.04
          #   target: x86_64-unknown-freebsd

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release --bin ecc"
          strip: true

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ecc
          target: ${{ matrix.platform.target }}
